name: Notify on New Card

on:
  schedule:
    - cron: "*/1 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install firebase-admin

      - name: Run notification script
        run: node send_fcm_notification.js

        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./hide-app-7cfe2-firebase-adminsdk-s0v49-1bbf26aa3a.json
